name: Notify Discord on PR creation

on:
  pull_request:
    types: [opened, reopened]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send PR notification to Discord
        uses: Ilshidur/action-discord@v2
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          message: 'A new pull request has been created: ${{ github.event.pull_request.title }}'
